package net.tardis.mod.client.models.clothing;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.tardis.mod.client.models.BodyPartHook;

public class ModelSpaceChest extends ModelBiped
{
    //fields
    private ModelRenderer Torso1;
    private ModelRenderer Torso2;
    private ModelRenderer Torso3;
    private ModelRenderer Torso4;
    private ModelRenderer Torso5;
    private ModelRenderer Torso6;
    private ModelRenderer Torso7;
    private ModelRenderer Torso8;
    private ModelRenderer Torso9;
    private ModelRenderer Torso10;
    private ModelRenderer Torso11;
    private ModelRenderer RightArm1;
    private ModelRenderer RightArm2;
    private ModelRenderer RightArm3;
    private ModelRenderer RightArm4;
    private ModelRenderer RightArm5;
    private ModelRenderer RightArm6;
    private ModelRenderer RightArm7;
    private ModelRenderer RightArm8;
    private ModelRenderer RightArm9;
    private ModelRenderer RightArm10;
    private ModelRenderer LeftArm1;
    private ModelRenderer LeftArm2;
    private ModelRenderer LeftArm3;
    private ModelRenderer LeftArm4;
    private ModelRenderer LeftArm5;
    private ModelRenderer LeftArm6;
    private ModelRenderer LeftArm7;
    private ModelRenderer LeftArm8;
    private ModelRenderer LeftArm9;
    private ModelRenderer LeftArm10;
    private ModelRenderer LeftArm11;

    public ModelSpaceChest() {
        textureWidth = 128;
        textureHeight = 128;

        Torso1 = new ModelRenderer(this, 115, 33);
        Torso1.addBox(2.5F, 0F, -2.5F, 1, 12, 1);
        Torso1.setRotationPoint(0F, 0F, 0F);
        Torso1.setTextureSize(128, 128);
        Torso1.mirror = true;
        setRotation(Torso1, 0F, 0F, 0.0174533F);
        Torso2 = new ModelRenderer(this, 0, 53);
        Torso2.addBox(3.3F, 0F, -2F, 1, 12, 4);
        Torso2.setRotationPoint(0F, 0F, 0F);
        Torso2.setTextureSize(128, 128);
        Torso2.mirror = true;
        setRotation(Torso2, 0F, 0F, 0F);
        Torso3 = new ModelRenderer(this, 13, 53);
        Torso3.addBox(-4F, 0F, 1.3F, 8, 12, 1);
        Torso3.setRotationPoint(0F, 0F, 0F);
        Torso3.setTextureSize(128, 128);
        Torso3.mirror = true;
        setRotation(Torso3, 0F, 0F, 0F);
        Torso4 = new ModelRenderer(this, 0, 53);
        Torso4.addBox(-4.3F, 0F, -2F, 1, 12, 4);
        Torso4.setRotationPoint(0F, 0F, 0F);
        Torso4.setTextureSize(128, 128);
        Torso4.mirror = true;
        setRotation(Torso4, 0F, 0F, 0F);
        Torso5 = new ModelRenderer(this, 0, 71);
        Torso5.addBox(-4F, -0.3F, -2F, 8, 1, 4);
        Torso5.setRotationPoint(0F, 0F, 0F);
        Torso5.setTextureSize(128, 128);
        Torso5.mirror = true;
        setRotation(Torso5, 0F, 0F, 0F);
        Torso6 = new ModelRenderer(this, 23, 22);
        Torso6.addBox(-0.5F, 4.1F, -2.5F, 1, 8, 1);
        Torso6.setRotationPoint(0F, 0F, 0F);
        Torso6.setTextureSize(128, 128);
        Torso6.mirror = true;
        setRotation(Torso6, 0F, 0F, 0F);
        Torso7 = new ModelRenderer(this, 34, 54);
        Torso7.addBox(-0.5F, 0F, 1.5F, 1, 12, 1);
        Torso7.setRotationPoint(0F, 0F, 0F);
        Torso7.setTextureSize(128, 128);
        Torso7.mirror = true;
        setRotation(Torso7, 0F, 0F, 0F);
        Torso8 = new ModelRenderer(this, 115, 33);
        Torso8.addBox(-3.5F, 0F, -2.5F, 1, 12, 1);
        Torso8.setRotationPoint(0F, 0F, 0F);
        Torso8.setTextureSize(128, 128);
        Torso8.mirror = true;
        setRotation(Torso8, 0F, 0F, -0.0174533F);
        Torso9 = new ModelRenderer(this, 16, 23);
        Torso9.addBox(1.5F, 0F, 1.5F, 1, 4, 1);
        Torso9.setRotationPoint(0F, 0F, 0F);
        Torso9.setTextureSize(128, 128);
        Torso9.mirror = true;
        setRotation(Torso9, 0F, 0F, 0.4886922F);
        Torso10 = new ModelRenderer(this, 13, 53);
        Torso10.addBox(-4F, 0F, -2.3F, 8, 12, 1);
        Torso10.setRotationPoint(0F, 0F, 0F);
        Torso10.setTextureSize(128, 128);
        Torso10.mirror = true;
        setRotation(Torso10, 0F, 0F, 0F);
        Torso11 = new ModelRenderer(this, 16, 23);
        Torso11.addBox(-2.5F, 0F, 1.5F, 1, 4, 1);
        Torso11.setRotationPoint(0F, 0F, 0F);
        Torso11.setTextureSize(128, 128);
        Torso11.mirror = true;
        setRotation(Torso11, 0F, 0F, -0.4886922F);
        RightArm1 = new ModelRenderer(this, 40, 53);
        RightArm1.addBox(-3.3F, -2F, -2F, 1, 9, 4);
        RightArm1.setRotationPoint(-5F, 2F, 0F);
        RightArm1.setTextureSize(128, 128);
        RightArm1.mirror = true;
        setRotation(RightArm1, 0F, 0F, 0F);
        RightArm2 = new ModelRenderer(this, 53, 54);
        RightArm2.addBox(-3F, -2F, 1.3F, 4, 9, 1);
        RightArm2.setRotationPoint(-5F, 2F, 0F);
        RightArm2.setTextureSize(128, 128);
        RightArm2.mirror = true;
        setRotation(RightArm2, 0F, 0F, 0F);
        RightArm3 = new ModelRenderer(this, 65, 51);
        RightArm3.addBox(-3F, 7F, 1.2F, 4, 3, 1);
        RightArm3.setRotationPoint(-5F, 2F, 0F);
        RightArm3.setTextureSize(128, 128);
        RightArm3.mirror = true;
        setRotation(RightArm3, 0F, 0F, 0F);
        RightArm4 = new ModelRenderer(this, 65, 57);
        RightArm4.addBox(-3.2F, 7F, -2F, 1, 3, 4);
        RightArm4.setRotationPoint(-5F, 2F, 0F);
        RightArm4.setTextureSize(128, 128);
        RightArm4.mirror = true;
        setRotation(RightArm4, 0F, 0F, 0F);
        RightArm5 = new ModelRenderer(this, 40, 53);
        RightArm5.addBox(0.3F, -2F, -2F, 1, 9, 4);
        RightArm5.setRotationPoint(-5F, 2F, 0F);
        RightArm5.setTextureSize(128, 128);
        RightArm5.mirror = true;
        setRotation(RightArm5, 0F, 0F, 0F);
        RightArm6 = new ModelRenderer(this, 77, 51);
        RightArm6.addBox(-3F, -2.3F, -2F, 4, 1, 4);
        RightArm6.setRotationPoint(-5F, 2F, 0F);
        RightArm6.setTextureSize(128, 128);
        RightArm6.mirror = true;
        setRotation(RightArm6, 0F, 0F, 0F);
        RightArm7 = new ModelRenderer(this, 53, 54);
        RightArm7.addBox(-3F, -2F, -2.3F, 4, 9, 1);
        RightArm7.setRotationPoint(-5F, 2F, 0F);
        RightArm7.setTextureSize(128, 128);
        RightArm7.mirror = true;
        setRotation(RightArm7, 0F, 0F, 0F);
        RightArm8 = new ModelRenderer(this, 78, 58);
        RightArm8.addBox(-3F, 9.2F, -2F, 4, 1, 4);
        RightArm8.setRotationPoint(-5F, 2F, 0F);
        RightArm8.setTextureSize(128, 128);
        RightArm8.mirror = true;
        setRotation(RightArm8, 0F, 0F, 0F);
        RightArm9 = new ModelRenderer(this, 65, 57);
        RightArm9.addBox(0.2F, 7F, -2F, 1, 3, 4);
        RightArm9.setRotationPoint(-5F, 2F, 0F);
        RightArm9.setTextureSize(128, 128);
        RightArm9.mirror = true;
        setRotation(RightArm9, 0F, 0F, 0F);
        RightArm10 = new ModelRenderer(this, 65, 51);
        RightArm10.addBox(-3F, 7F, -2.2F, 4, 3, 1);
        RightArm10.setRotationPoint(-5F, 2F, 0F);
        RightArm10.setTextureSize(128, 128);
        RightArm10.mirror = true;
        setRotation(RightArm10, 0F, 0F, 0F);
        LeftArm1 = new ModelRenderer(this, 65, 57);
        LeftArm1.addBox(2.2F, 7F, -2F, 1, 3, 4);
        LeftArm1.setRotationPoint(5F, 2F, 0F);
        LeftArm1.setTextureSize(128, 128);
        LeftArm1.mirror = true;
        setRotation(LeftArm1, 0F, 0F, 0F);
        LeftArm2 = new ModelRenderer(this, 114, 14);
        LeftArm2.addBox(2.5F, 2F, -1F, 1, 4, 2);
        LeftArm2.setRotationPoint(5F, 2F, 0F);
        LeftArm2.setTextureSize(128, 128);
        LeftArm2.mirror = true;
        setRotation(LeftArm2, 0F, 0F, 0F);
        LeftArm3 = new ModelRenderer(this, 77, 51);
        LeftArm3.addBox(-1F, -2.3F, -2F, 4, 1, 4);
        LeftArm3.setRotationPoint(5F, 2F, 0F);
        LeftArm3.setTextureSize(128, 128);
        LeftArm3.mirror = true;
        setRotation(LeftArm3, 0F, 0F, 0F);
        LeftArm3.mirror = false;
        LeftArm4 = new ModelRenderer(this, 53, 54);
        LeftArm4.addBox(-1F, -2F, 1.3F, 4, 9, 1);
        LeftArm4.setRotationPoint(5F, 2F, 0F);
        LeftArm4.setTextureSize(128, 128);
        LeftArm4.mirror = true;
        setRotation(LeftArm4, 0F, 0F, 0F);
        LeftArm4.mirror = false;
        LeftArm5 = new ModelRenderer(this, 65, 51);
        LeftArm5.addBox(-1F, 7F, 1.2F, 4, 3, 1);
        LeftArm5.setRotationPoint(5F, 2F, 0F);
        LeftArm5.setTextureSize(128, 128);
        LeftArm5.mirror = true;
        setRotation(LeftArm5, 0F, 0F, 0F);
        LeftArm5.mirror = false;
        LeftArm6 = new ModelRenderer(this, 53, 54);
        LeftArm6.addBox(-1F, -2F, -2.3F, 4, 9, 1);
        LeftArm6.setRotationPoint(5F, 2F, 0F);
        LeftArm6.setTextureSize(128, 128);
        LeftArm6.mirror = true;
        setRotation(LeftArm6, 0F, 0F, 0F);
        LeftArm6.mirror = false;
        LeftArm7 = new ModelRenderer(this, 40, 16);
        LeftArm7.addBox(-1.3F, -2F, -2F, 1, 9, 4);
        LeftArm7.setRotationPoint(5F, 2F, 0F);
        LeftArm7.setTextureSize(128, 128);
        LeftArm7.mirror = true;
        setRotation(LeftArm7, 0F, 0F, 0F);
        LeftArm8 = new ModelRenderer(this, 78, 58);
        LeftArm8.addBox(-1F, 9.2F, -2F, 4, 1, 4);
        LeftArm8.setRotationPoint(5F, 2F, 0F);
        LeftArm8.setTextureSize(128, 128);
        LeftArm8.mirror = true;
        setRotation(LeftArm8, 0F, 0F, 0F);
        LeftArm8.mirror = false;
        LeftArm9 = new ModelRenderer(this, 97, 56);
        LeftArm9.addBox(-1.2F, 7F, -2F, 1, 3, 4);
        LeftArm9.setRotationPoint(5F, 2F, 0F);
        LeftArm9.setTextureSize(128, 128);
        LeftArm9.mirror = true;
        setRotation(LeftArm9, 0F, 0F, 0F);
        LeftArm10 = new ModelRenderer(this, 65, 51);
        LeftArm10.addBox(-1F, 7F, -2.2F, 4, 3, 1);
        LeftArm10.setRotationPoint(5F, 2F, 0F);
        LeftArm10.setTextureSize(128, 128);
        LeftArm10.mirror = true;
        setRotation(LeftArm10, 0F, 0F, 0F);
        LeftArm10.mirror = false;
        LeftArm11 = new ModelRenderer(this, 40, 53);
        LeftArm11.addBox(2.3F, -2F, -2F, 1, 9, 4);
        LeftArm11.setRotationPoint(5F, 2F, 0F);
        LeftArm11.setTextureSize(128, 128);
        LeftArm11.mirror = true;
        setRotation(LeftArm11, 0F, 0F, 0F);


        //Torse - Init
        bipedBody = new BodyPartHook(this, 16, 16);
        bipedBody.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.0F);
        bipedBody.setRotationPoint(0.0F, 0.0F, 0.0F);

        //Torso - Render
        ((BodyPartHook) bipedBody).setRender(scale -> {
            GlStateManager.pushMatrix();
            Torso1.renderWithRotation(scale);
            Torso2.renderWithRotation(scale);
            Torso3.renderWithRotation(scale);
            Torso4.renderWithRotation(scale);
            Torso5.renderWithRotation(scale);
            Torso6.renderWithRotation(scale);
            Torso7.renderWithRotation(scale);
            Torso8.renderWithRotation(scale);
            Torso9.renderWithRotation(scale);
            Torso10.renderWithRotation(scale);
            Torso11.renderWithRotation(scale);
            GlStateManager.popMatrix();
        });

        //Right Arm - Init
        this.bipedRightArm = new BodyPartHook(this, 40, 16);
        this.bipedRightArm.setRotationPoint(-5.0F, 2.0F, 0.0F);

        //Right Arm - Render
        ((BodyPartHook) bipedRightArm).setRender(scale -> {
            GlStateManager.pushMatrix();
            GlStateManager.translate(0.3, -0.11, 0);
            RightArm1.renderWithRotation(scale);
            RightArm2.renderWithRotation(scale);
            RightArm3.renderWithRotation(scale);
            RightArm4.renderWithRotation(scale);
            RightArm5.renderWithRotation(scale);
            RightArm6.renderWithRotation(scale);
            RightArm7.renderWithRotation(scale);
            RightArm8.renderWithRotation(scale);
            RightArm9.renderWithRotation(scale);
            RightArm10.renderWithRotation(scale);
            GlStateManager.popMatrix();
        });

        //Left Arm - Init
        this.bipedLeftArm = new BodyPartHook(this, 40, 16);
        this.bipedLeftArm.setRotationPoint(5.0F, 2.0F, 0.0F);


        //Left Arm - Init
        ((BodyPartHook) bipedLeftArm).setRender(scale -> {
            GlStateManager.pushMatrix();
            GlStateManager.translate(-0.3, -0.11, 0);
            LeftArm1.renderWithRotation(scale);
            LeftArm2.renderWithRotation(scale);
            LeftArm3.renderWithRotation(scale);
            LeftArm4.renderWithRotation(scale);
            LeftArm5.renderWithRotation(scale);
            LeftArm6.renderWithRotation(scale);
            LeftArm7.renderWithRotation(scale);
            LeftArm8.renderWithRotation(scale);
            LeftArm9.renderWithRotation(scale);
            LeftArm10.renderWithRotation(scale);
            LeftArm11.renderWithRotation(scale);
            GlStateManager.popMatrix();
        });
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
    }

}
